//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silverlight.UI.Esri.JTToolbarCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolbarCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolbarCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Silverlight.UI.Esri.JTToolbarCommon.Resources.ToolbarCommon", typeof(ToolbarCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new layer.
        /// </summary>
        public static string AddLayerTip {
            get {
                return ResourceManager.GetString("AddLayerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address locator.
        /// </summary>
        public static string AddresLocatorTip {
            get {
                return ResourceManager.GetString("AddresLocatorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark of locations.
        /// </summary>
        public static string BookmarkTip {
            get {
                return ResourceManager.GetString("BookmarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage description.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour .
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours .
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info feature.
        /// </summary>
        public static string InfoTip {
            get {
                return ResourceManager.GetString("InfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search address.
        /// </summary>
        public static string LocateAddressTip {
            get {
                return ResourceManager.GetString("LocateAddressTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string MeasureTip {
            get {
                return ResourceManager.GetString("MeasureTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute .
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes .
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookmarks available!.
        /// </summary>
        public static string NoBookmarksAvailable {
            get {
                return ResourceManager.GetString("NoBookmarksAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers available!.
        /// </summary>
        public static string NoLayersAvailable {
            get {
                return ResourceManager.GetString("NoLayersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string PanTip {
            get {
                return ResourceManager.GetString("PanTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected layer from the map.
        /// </summary>
        public static string RemoveLayerTip {
            get {
                return ResourceManager.GetString("RemoveLayerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Route.
        /// </summary>
        public static string RouteClearTip {
            get {
                return ResourceManager.GetString("RouteClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start routing calculation.
        /// </summary>
        public static string RouteStartTip {
            get {
                return ResourceManager.GetString("RouteStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 2 location must be selected.
        /// </summary>
        public static string SelectMin2Locations {
            get {
                return ResourceManager.GetString("SelectMin2Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ZoomInTip {
            get {
                return ResourceManager.GetString("ZoomInTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ZoomOutTip {
            get {
                return ResourceManager.GetString("ZoomOutTip", resourceCulture);
            }
        }
    }
}
