//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silverlight.UI.Esri.JTToolbarEditGeneral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolbarEditGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolbarEditGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Silverlight.UI.Esri.JTToolbarEditGeneral.Resources.ToolbarEditGeneral", typeof(ToolbarEditGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New geometry.
        /// </summary>
        public static string AddGeometryTip {
            get {
                return ResourceManager.GetString("AddGeometryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel updates.
        /// </summary>
        public static string CancelUpdateTip {
            get {
                return ResourceManager.GetString("CancelUpdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        public static string ClearSelectionTip {
            get {
                return ResourceManager.GetString("ClearSelectionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create polygon from points.
        /// </summary>
        public static string CreatePoint2PolygonTip {
            get {
                return ResourceManager.GetString("CreatePoint2PolygonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete geometrie.
        /// </summary>
        public static string DeleteGeometryTip {
            get {
                return ResourceManager.GetString("DeleteGeometryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attributes.
        /// </summary>
        public static string EditAttributesTip {
            get {
                return ResourceManager.GetString("EditAttributesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vertices.
        /// </summary>
        public static string EditGeometryTip {
            get {
                return ResourceManager.GetString("EditGeometryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge polygons.
        /// </summary>
        public static string MergePolygonTip {
            get {
                return ResourceManager.GetString("MergePolygonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Point.
        /// </summary>
        public static string MovePointTip {
            get {
                return ResourceManager.GetString("MovePointTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point to polygon.
        /// </summary>
        public static string Point2PolygonTip {
            get {
                return ResourceManager.GetString("Point2PolygonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save updates.
        /// </summary>
        public static string SaveTip {
            get {
                return ResourceManager.GetString("SaveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select geometries.
        /// </summary>
        public static string SelectGeometriesTip {
            get {
                return ResourceManager.GetString("SelectGeometriesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap polygons.
        /// </summary>
        public static string Snap2PolygonTip {
            get {
                return ResourceManager.GetString("Snap2PolygonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split polygon.
        /// </summary>
        public static string SplitPolygonTip {
            get {
                return ResourceManager.GetString("SplitPolygonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox geoprocessing not yet implemented.
        /// </summary>
        public static string ToolboxNotImplemented {
            get {
                return ResourceManager.GetString("ToolboxNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing Toolbox.
        /// </summary>
        public static string ToolboxTip {
            get {
                return ResourceManager.GetString("ToolboxTip", resourceCulture);
            }
        }
    }
}
