//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silverlight.UI.Esri.JTToc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Toc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Toc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Silverlight.UI.Esri.JTToc.Resources.Toc", typeof(Toc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute List.
        /// </summary>
        public static string AttributeList {
            get {
                return ResourceManager.GetString("AttributeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto zoom to selected.
        /// </summary>
        public static string AutoZoom {
            get {
                return ResourceManager.GetString("AutoZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel selected rows.
        /// </summary>
        public static string CancelSelectedRows {
            get {
                return ResourceManager.GetString("CancelSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel selections.
        /// </summary>
        public static string CancelSelections {
            get {
                return ResourceManager.GetString("CancelSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse selections.
        /// </summary>
        public static string ReverseSelections {
            get {
                return ResourceManager.GetString("ReverseSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Layer.
        /// </summary>
        public static string ZoomLayer {
            get {
                return ResourceManager.GetString("ZoomLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom selected.
        /// </summary>
        public static string ZoomSelected {
            get {
                return ResourceManager.GetString("ZoomSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to selection.
        /// </summary>
        public static string ZoomSelection {
            get {
                return ResourceManager.GetString("ZoomSelection", resourceCulture);
            }
        }
    }
}
